### ISSUE TITLE
Paleo Dates - User Interface Requests

### ISSUE THREAD

**Issue by wendy144** [cedardevs/feedback#4]
I. Incorporate geologic time-frames (epochs, or other significant time periods/ranges) into the user interface as well as providing the end-user with the ability to enter start and end dates (years)

To date (2019 0510) World Data Service for Paleoclimatology (WDS-Paleo) SMEs suggest the following list of six items. This list also includes the description of the significance of each item - which is not meant for display in user interface but may be documented via help or some other artifact. 

**1) Holocene** (defined by geologic time-scale - Dates TBD - WDS-Paleo will provide dates)
_The Holocene is considered by some to be an interglacial period within the Pleistocene Epoch. The Holocene has seen the growth and impacts of the human species worldwide, including all its written history, development of major civilizations, and overall significant transition toward urban living in the present._

**2) Last Deglaciation**  (Not part of official geologic time-scale - Dates TBD - WDS-Paleo will provide dates)
_Deglaciation describes the transition from full glacial conditions during ice ages, to warm interglacials, characterized by global warming and sea level rise due to change in continental ice volume. Thus, it refers to the retreat of a glacier, an ice sheet or frozen surface layer, and the resulting exposure of the Earth's surface. The decline of the cryosphere due to ablation can occur on any scale from global to localized to a particular glacier.[citation needed] After the Last Glacial Maximum (ca. 21,000 years ago), the last deglaciation begun, which lasted until the early Holocene. Around much of Earth, deglaciation during the last 100 years has been accelerating as a result of climate change, partly brought on by anthropogenic changes to greenhouse gases._

**3) Last Glacial Maximum (LGM)** (Not part of official geologic time-scale - Dates TBD - WDS-Paleo will provide dates)
_The Last Glacial Maximum (LGM) was the most recent time during the Last Glacial Period when ice sheets were at their greatest extent. Vast ice sheets covered much of North America, northern Europe, and Asia. The ice sheets profoundly affected Earth's climate by causing drought, desertification, and a large drop in sea levels. The ice sheets reached their maximum coverage about 26,500 years ago (26.5 ka BP)._ 

**4) Last Interglacial**  (Not part of official geologic time-scale - Dates TBD - WDS-Paleo will provide dates)
_An interglacial period (or alternatively interglacial, interglaciation) is a geological interval of warmer global average temperature lasting thousands of years that separates consecutive glacial periods within an ice age._

**5) Pliocene** (defined by geologic time-scale - Dates TBD - WDS-Paleo will provide dates)
__During the Pliocene epoch (5.3 Ma to 2.6 Ma) climate became cooler and drier, and seasonal, similar to modern climates. Which is of exceptional importance because it has provided the longest continuous late Cenozoic land-based sedimentary record thus far. The Pliocene has a role in assessing future climate impacts._ 

**6) Eocene Thermal Maximum (PETM)**  (Not part of official geologic time-scale - Dates TBD -  WDS-Paleo will provide dates) 
_PETM is one of the most intense and abrupt intervals of global warming in the geological record. It occurred around 56 million years ago, at the boundary between the Paleocene and Eocene epochs._

**Comment by mcquinne** [comment]
This is awesome information, Wendy. Thank you!

I'm curious: are you aware of other groups in NCEI (or NOAA as a whole I guess) that manage data on the paleo time scale that might be interested in defining their own time ranges of interest? e.g. do you think the official geological time scale would be useful in addition to these time periods?

**Comment by ajakz** [comment]
Closing as this feature was added to the UI! See cedardevs/onestop#654
