### ISSUE TITLE
Tech help link / ISO examples

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/feedback#7]
On Monday 5/20 we had a meeting with metadata folks and generated some ideas on documentation.

- [ ] Include a section for more technical help (or links to docs) on the Help page of OneStop
- [ ] Include more specific examples for ISO parsing. It would be useful to see examples of ISO connected to how it will be rendered in OneStop

**Comment by ajakz** [comment]
Adding these tasks to cedardevs/onestop#1049
