### ISSUE TITLE
Deleting filter after query term cleared causes the filter removed

### ISSUE THREAD

**Issue by chris-noaa-affiliate** [cedardevs/feedback#8]
**Describe the bug**

Clearing the query term from the OneStop search UI and then deleting the filter (in this example the keyword filter) returns No Results without the keywords on the left being reset. Note, this is only an issue when the last filter is deleted. This behavior happens for any of the types of filters. If there are 2 or more filters applied to a search deleting one of the filters with the query term cleared executes successfully. 

**To Reproduce**
1. Go to https://data.noaa.gov/onestop/collections?q=climate&f=science:Climate%20Indicators%20>%20Atmospheric%2FOcean%20Indicators%20>%20Sea%20Surface%20Temperature%20Indices%20>%20Oceanic%20Nino%20Index

2. Click on X to remove the "climate" query term and then click on the X to remove the "Oceanic Nino Index" keyword filter.

3. Expand the keyword > Data Theme > Climate Indicators > Atmospheric/Ocean Indicators > Sea Surface Temperature Indices > Ocean Nino Index

4. The Ocean Nino Index keyword shows 1 record while the search results show No Results

**Expected behavior**
The keywords should have been reset. 

**Screenshots**
I've attached a few screenshots showing the behavior with deleting one of 2 filters and then deleting the last filter after the query term is cleared. 

<img width="1421" alt="one-filter-with-query-cleared" src="https://user-images.githubusercontent.com/29871707/65286109-a1572480-dafb-11e9-9620-a222cd02ca8c.png">
<img width="1426" alt="one-filter-with-filter-deleted-after-query-cleared" src="https://user-images.githubusercontent.com/29871707/65286183-dbc0c180-dafb-11e9-9290-956aa4c68e19.png">

<img width="1444" alt="two-filters-with-query-cleared" src="https://user-images.githubusercontent.com/29871707/65286104-a0be8e00-dafb-11e9-8dd5-97e95c34ee22.png">
<img width="1441" alt="two-filters-with-one-deleted-after-query-cleared" src="https://user-images.githubusercontent.com/29871707/65286107-a0be8e00-dafb-11e9-8a6e-3ab79dae13e8.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 77.0.3865.75 (Official Build) (64-bit)

**Additional context**
Although you can't can't execute a filter using keywords without first searching using a query term in the OneStop UI, you can use a keyword filter without a query term using the OneStop API. The following search works to filter for records with the Oceanic Nino Index keyword.

https://data.noaa.gov/onestop/collections?f=science:Climate%20Indicators%20>%20Atmospheric%2FOcean%20Indicators%20>%20Sea%20Surface%20Temperature%20Indices%20>%20Oceanic%20Nino%20Index

**Comment by zebdelk** [comment]
This has been fixed in the latest release of OneStop. I just confirmed that it's working correctly in version 2.3.0.
